//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACServices.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbComercio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbComercio()
        {
            this.tbUsuario = new HashSet<tbUsuario>();
        }
    
        public int com_id { get; set; }
        public int ven_id { get; set; }
        public string com_nombre_fantasia { get; set; }
        public int com_cuit { get; set; }
        public string com_calle { get; set; }
        public Nullable<int> com_numero { get; set; }
    
        public virtual tbVendor tbVendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUsuario> tbUsuario { get; set; }
    }
}
