//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACServices.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCuestionarioPregunta
    {
        public int cue_id { get; set; }
        public int pre_id { get; set; }
        public bool cpr_respuesta { get; set; }
        public string cpr_comentario { get; set; }
    
        public virtual tbCuestionario tbCuestionario { get; set; }
        public virtual tbPregunta tbPregunta { get; set; }
    }
}
