//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACServices.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCuestionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCuestionario()
        {
            this.tbCuestionarioPregunta = new HashSet<tbCuestionarioPregunta>();
        }
    
        public int cue_id { get; set; }
        public int pac_id { get; set; }
        public System.DateTime cue_fecha { get; set; }
        public bool cue_diagnostico { get; set; }
        public string cue_latitud { get; set; }
        public string cue_longitud { get; set; }
    
        public virtual tbPaciente tbPaciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCuestionarioPregunta> tbCuestionarioPregunta { get; set; }
    }
}
