//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACServices.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRequestPaymentVendor
    {
        public int pde_id { get; set; }
        public System.DateTime rpv_request_fecha { get; set; }
        public string rpv_request_body { get; set; }
        public Nullable<System.DateTime> rpv_response_fecha { get; set; }
        public string rpv_response_body { get; set; }
    
        public virtual tbPaymentDetail tbPaymentDetail { get; set; }
    }
}
