//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACServices.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUsuario()
        {
            this.tbPayment = new HashSet<tbPayment>();
        }
    
        public int usu_id { get; set; }
        public Nullable<int> com_id { get; set; }
        public string usu_usuario { get; set; }
        public string usu_password { get; set; }
        public string usu_refresh_token { get; set; }
        public bool usu_active { get; set; }
    
        public virtual tbComercio tbComercio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPayment> tbPayment { get; set; }
    }
}
