//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACServices.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbVendor()
        {
            this.tbComercio = new HashSet<tbComercio>();
        }
    
        public int ven_id { get; set; }
        public string ven_nombre { get; set; }
        public string ven_parameters { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbComercio> tbComercio { get; set; }
    }
}
